services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - todo-net

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/data/todolist.db
    volumes:
      - sqlite_data:/data
    networks:
      - todo-net



  prometheus:
    image: prom/prometheus:v2.45.0 
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml
    networks:
      - todo-net

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3001:3000"
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - todo-net


networks:
  todo-net:
    driver: bridge

volumes:
  sqlite_data: