services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - todo-net

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - todo-net


  prometheus:
    image: prom/prometheus:v2.45.0 
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge

volumes:
  sqlite_data: